### ISSUE TITLE
vignettes DT complains 

### ISSUE THREAD

**Issue by trotsiuk** [pschmidtwalter/LWFBrook90R#9]
When trying to build a source package in R I'm getting an issue

```
Updating LWFBrook90R documentation
Warning: @examples [/Users/trotsiuv/Documents/work/papers/2019_Walter_brook90/analysis/LWFBrook90R/R/approx_standprop.R#32]: requires a value
Warning: @format [/Users/trotsiuv/Documents/work/papers/2019_Walter_brook90/analysis/LWFBrook90R/R/data.R#6]: mismatched braces or quotes
Warning: @examples [/Users/trotsiuv/Documents/work/papers/2019_Walter_brook90/analysis/LWFBrook90R/R/mrun_helper_combinations.R#15]: requires a value
Warning: @examples [/Users/trotsiuv/Documents/work/papers/2019_Walter_brook90/analysis/LWFBrook90R/R/soil_to_param.R#10]: requires a value
Writing NAMESPACE
Loading LWFBrook90R
Writing NAMESPACE
Updating vignettes
Documentation completed

==> devtools::build()

✔  checking for file ‘/Users/trotsiuv/Documents/work/papers/2019_Walter_brook90/analysis/LWFBrook90R/DESCRIPTION’ ...
─  preparing ‘LWFBrook90R’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  installing the package to build vignettes
E  creating vignettes (9s)
   Quitting from lines 111-112 (intro_lwfbrook90r.Rmd) 
   Error: processing vignette 'intro_lwfbrook90r.Rmd' failed with diagnostics:
   Check that is.data.table(DT) == TRUE. Otherwise, := and `:=`(...) are defined for use in j, once only and in particular ways. See help(":=").
   Execution halted
Error in (function (command = NULL, args = character(), error_on_status = TRUE,  : 
  System command error
Calls: <Anonymous> ... eval -> with_envvar -> force -> do.call -> <Anonymous>
Execution halted

Exited with status 1.


```

**Comment by fabern** [comment]
Hi,

Installing the package I get a similar error message regarding the generation of the vignettes. I'm installing with: `devtools::install_url("https://github.com/pschmidtwalter/LWFBrook90R/archive/v0.3.4.tar.gz", dependencies = T, build_vignettes = T)` 

The same error apperas in version `0.3.4` as well as `0.2.0`. Setting `build_vignettes = F` successfully installs the package on my macOS machine (yet gfortran throws some warnings (for output see below)).

Was that issue solved in the meantime tow work with `build_vignettes = T`?


**`build_vignettes = T`:**
```
> devtools::install_url("https://github.com/pschmidtwalter/LWFBrook90R/archive/v0.3.4.tar.gz", dependencies = T, build_vignettes = T)
Downloading package from url: https://github.com/pschmidtwalter/LWFBrook90R/archive/v0.3.4.tar.gz
✓  checking for file ‘/private/var/folders/qq/vp0w5lnd5xbc2p_y48b0zl200024c1/T/RtmpYyaygn/remotes102916e761b88/LWFBrook90R-0.3.4/DESCRIPTION’ ...
─  preparing ‘LWFBrook90R’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  installing the package to build vignettes
E  creating vignettes (6.5s)
   --- re-building ‘intro_lwfbrook90r.Rmd’ using rmarkdown
   Warning: The vignette title specified in \VignetteIndexEntry{} is different from the title in the YAML metadata. The former is ""Introduction to LWFBrook90R"", and the latter is "Introduction to LWFBrook90R". If that is intentional, you may set options(rmarkdown.html_vignette.check_title = FALSE) to suppress this check.
   pandoc-citeproc: Error in $: Incompatible API versions: encoded with [1,21] but attempted to decode with [1,20].
   CallStack (from HasCallStack):
     error, called at ./Text/Pandoc/JSON.hs:112:48 in pandoc-types-1.20-KTt4MbZ4Xnw3N9yUroj6oX:Text.Pandoc.JSON
   Error running filter /usr/local/bin/pandoc-citeproc:
   Filter returned error status 1
   Error: processing vignette 'intro_lwfbrook90r.Rmd' failed with diagnostics:
   pandoc document conversion failed with error 83
   --- failed re-building ‘intro_lwfbrook90r.Rmd’
   
   SUMMARY: processing the following file failed:
     ‘intro_lwfbrook90r.Rmd’
   
   Error: Vignette re-building failed.
   Execution halted
Error: Failed to install 'unknown package' from URL:
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> Filter returned error status 1
E> Error: processing vignette 'intro_lwfbrook90r.Rmd' failed with diagnostics:
E> pandoc document conversion failed with error 83
E> --- failed re-building ‘intro_lwfbrook90r.Rmd’
E> 
E> SUMMARY: processing the following file failed:
E>   ‘intro_lwfbrook90r.Rmd’
E> 
E> Error: Vignette re-building failed.
E> Execution halted
```

**`build_vignettes = F`:**
```
> devtools::install_url("https://github.com/pschmidtwalter/LWFBrook90R/archive/v0.3.4.tar.gz", dependencies = T, build_vignettes = F)
Downloading package from url: https://github.com/pschmidtwalter/LWFBrook90R/archive/v0.3.4.tar.gz
✓  checking for file ‘/private/var/folders/qq/vp0w5lnd5xbc2p_y48b0zl200024c1/T/RtmpYyaygn/remotes1029135186419/LWFBrook90R-0.3.4/DESCRIPTION’ ...
─  preparing ‘LWFBrook90R’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘LWFBrook90R_0.3.4.tar.gz’
   Warning: invalid uid value replaced by that for user 'nobody'
   
* installing *source* package ‘LWFBrook90R’ ...
** using staged installation
** libs
gfortran  -fPIC  -Wall -g -O2  -c  brook90.f95 -o brook90.o
VARDCL.h:175:28:

  175 | real(kind=8) :: Par(MPar,ML)    ! hydraulic parameters for layer
      |                            1
Warning: Array 'par' at (1) is larger than limit set by '-fmax-stack-var-size=', moved from stack to static storage. This makes the procedure unsafe when called recursively, or concurrently from multiple threads. Consider using '-frecursive', or increase the '-fmax-stack-var-size=' limit, or change the code to use an ALLOCATABLE array. [-Wsurprising]
DOUTPUT.h:110:0:

  110 |     RELAWAT = AWAT / AWATFK
      | 
Warning: 'awatfk' may be used uninitialized in this function [-Wmaybe-uninitialized]
VARDCL.h:33:22:

   33 | real(kind=8) :: AWATFK          ! available soil water in root zone at field cap., mm, output only
      |                      ^
note: 'awatfk' was declared here
/usr/local/Cellar/gcc/10.2.0/bin/gcc-10 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c init.c -o init.o
/usr/local/Cellar/gcc/10.2.0/bin/gcc-10 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/Cellar/gcc/10.2.0/lib -o LWFBrook90R.so brook90.o init.o -L/usr/local/lib/gcc/10/gcc/x86_64-apple-darwin18/10.2.0/ -L/usr/local/lib/gcc/10 -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Library/Frameworks/R.framework/Versions/3.6/Resources/library/00LOCK-LWFBrook90R/00new/LWFBrook90R/libs
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (LWFBrook90R)
```

**Comment by pschmidtwalter** [comment]
This was solved a long time ago.
Please use the following command to install the package (also see the starting page of this repo for installation instruction):

```
if(!require("remotes")) install.packages("remotes")
remotes::install_github(repo="pschmidtwalter/LWFBrook90R", build_vignettes=TRUE,
                        ref="v0.3.4") 
```

**Comment by fabern** [comment]
Thanks for the quick reply. I retried it with `remotes::install_github(repo="pschmidtwalter/LWFBrook90R", build_vignettes=TRUE, ref="v0.3.4")` yet the same error message still appeared.

Judging by the error message, my errror is actually different from @trotsiuk's initial post. The real issue in my case is:
`pandoc-citeproc: Error in $: Incompatible API versions: encoded with [1,21] but attempted to decode with [1,20].`

It turned out, that my versions of `pandoc` (`pandoc -v`  ==> `2.2.3.2`) and `pandoc-citeproc` (`pandoc-citeproc -V`==> `0.16.4.1`) were not compatible with each other. Updating pandoc-citeproc to version `0.17.0.2` allowed me to successfully install LWFBrook90R.
